apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  labels:
    app: nfs-test
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "while true; do date >> /mnt/nfs/test.log; sleep 5; done"]
      volumeMounts:
        - mountPath: "/mnt/nfs"
          name: nfs-volume
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-test-service
spec:
  type: LoadBalancer
  selector:
    app: nfs-test
  ports:
    - port: 80
      targetPort: 80