---
- hosts: all
  become: true
  vars:
    nfs_export_dir: /srv/nfs_share
    nfs_network: "{{ nfs_network }}"

  tasks:
    - name: Install NFS server packages
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Create export directory
      file:
        path: "{{ nfs_export_dir }}"
        state: directory
        mode: '0777'

    - name: Configure /etc/exports
      copy:
        dest: /etc/exports
        content: "{{ nfs_export_dir }} {{ nfs_network }}(rw,sync,no_subtree_check,no_root_squash)\n"

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted
        enabled: true