apiVersion: v1
kind: Service
metadata:
  name: gaia-rpc
spec:
  type: LoadBalancer
  selector:
    app: gaia-node
  ports:
    - name: rpc
      port: 26657
      targetPort: 26657
    - name: p2p
      port: 26656
      targetPort: 26656